#T-218: country api + dashboard editor
ecoseller/ecoseller pull request #232
Opened 2023-05-11 12:48 UTC by michalpulpan

2023-05-11 14:13 UTC, VL-CZ commented
@michalpulpan 
You know, I'm something of generic view lover myself 😄

2023-05-13 08:27 UTC, lakatop requested changes

2023-05-13 08:27 UTC, lakatop commented on src/dashboard/pages/api/country/[code].tsx
> +  if (method === "PUT") {
Maybe I am missing something, but is it necessary to do swith here, when there is already one in the countryDetailAPI method?

2023-05-13 08:27 UTC, lakatop commented on src/dashboard/pages/api/country/index.tsx
> +  if (method === "POST") {
Same here.

2023-05-13 08:27 UTC, lakatop commented on src/dashboard/pages/api/product/price-list/index.ts
> +  if (method === "POST") {
Same.

2023-05-13 15:15 UTC, lakatop approved these changes

2023-05-13 17:00 UTC, merged